### ISSUE TITLE
Can't provision WiFi using EspTouch

### ISSUE THREAD

**Issue by jiangxw** [Xinyuan-LilyGO/T-Embed-CC1101#4]
I tried to configure WiFi and got a timeout. The "help" tells me to configure using EspTouch. So I followed, but the device doesn't show up in either EspTouch or EspTouch V2. How can I configure WiFi?

**Comment by ShallowGreen123** [comment]
1. To download the EspTouch software, you can scan the QR code below to download;
![image](https://github.com/user-attachments/assets/54f886a8-8be2-4d8e-9dca-81ae3c64bfda)

2. Enter EspTouch on your phone. Please note that your phone must be connected to WIIF first (not 5G), then click EspTouch.
![image](https://github.com/user-attachments/assets/6ee32022-7590-44dc-b77e-100ac5166d92)


3. Enter the WIFI password on your phone; the device should be in the WIFI interface;
![image](https://github.com/user-attachments/assets/0e8f8096-ed45-48a6-8e69-1b5ea2d713a9)

4. Click Confirm on your phone; click Config on your device; then wait for the network configuration to succeed;
![image](https://github.com/user-attachments/assets/fdc2857b-1245-465b-bd6d-2afeb7b88d27)

5. The following is a successful network configuration
![image](https://github.com/user-attachments/assets/c39375e9-1a41-4567-8d9c-38c9c1f34777)

**Comment by jiangxw** [comment]
That worked. thanks!

**Comment by tally0highwayman** [comment]
I followed these exact steps and they did not work on my new, out-of-the-box T-Embed C1101.
SF Version: v1.1-20250109
HD Version: v1.0-20240729
