### ISSUE TITLE
How do I turn on the device after I shut it down

### ISSUE THREAD

**Issue by jiangxw** [Xinyuan-LilyGO/T-Embed-CC1101#5]
I went to Settings -> Shutdown. But I can't find a way to turn it on by pushing the buttons. The only way I found is to connect to a computer using USB. How do I do that?

**Comment by ShallowGreen123** [comment]
When the device is turned off, you can turn it on by inserting a USB. Of course, you can also `long press` the power button on the back of the device.

![image](https://github.com/user-attachments/assets/726cff4a-efa2-4279-b57d-7193ef2d0d5c)

**Comment by jiangxw** [comment]
The long press did not work for me on my CC1101

**Comment by Huzzla101** [comment]
Also u have the deep sleep function that is almost like turn it off. if u use that then u can just click the top botton once to start it up
