### ISSUE TITLE
Help un-brick T-Embed-CC1101

### ISSUE THREAD

**Issue by xathugameboy** [Xinyuan-LilyGO/T-Embed-CC1101#8]
I tried installing 3rd firmware but it did not work. Installed factory firmware via flash_download_tool_3.9.7. My PC still detects the device (COMxx) when connected but the device does not turn on.
Please help me find out where to find firmware for the T-embed and how to take it back to "normal",

**Comment by ShallowGreen123** [comment]
If you plug in T-Embed-CC1101, the serial port can be detected, but it cannot be opened. This may be occupied by some applications. If you cannot find the occupied program, you can directly restart the computer.

You can burn `firmware/firmware_factory_test_20241014.bin` to restore it.

**Comment by xathugameboy** [comment]
> If you plug in T-Embed-CC1101, the serial port can be detected, but it cannot be opened. This may be occupied by some applications. If you cannot find the occupied program, you can directly restart the computer.
> 
> You can burn `firmware/firmware_factory_test_20241014.bin` to restore it.

Thanks for very quick replies. I burned firmware/firmware_factory_test_20241014.bin via flash_download_tool_3.9.7 successfully as the instructions in the files but the T-Embed still does not turn on. Could you provide a link or video installing it or webpages?

**Comment by ShallowGreen123** [comment]
Use flash_download_tool_3.9.7 to download the program, you need to press the reset key;

Open the back cover of the device and press the reset button in the following position, which may be difficult to press, you can take a thin object and poke it;

![image](https://github.com/user-attachments/assets/b753eba3-33f3-4c6e-aba7-cbca60ecbaa4)

**Comment by xathugameboy** [comment]
> Use flash_download_tool_3.9.7 to download the program, you need to press the reset key;
> 
> Open the back cover of the device and press the reset button in the following position, which may be difficult to press, you can take a thin object and poke it;
> 
> ![image](https://private-user-images.githubusercontent.com/67771110/383495371-b753eba3-33f3-4c6e-aba7-cbca60ecbaa4.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MzA4ODc5MDIsIm5iZiI6MTczMDg4NzYwMiwicGF0aCI6Ii82Nzc3MTExMC8zODM0OTUzNzEtYjc1M2ViYTMtMzNmMy00YzZlLWFiYTctY2JjYTYwZWNiYWE0LnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDExMDYlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQxMTA2VDEwMDY0MlomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTg5MjQwNDg2YTE2MDc5NjczZTkxODViODdkZDc3NmMzZGUzYzI2ZGYzNGI1MDZiOTMxOTM2OGMwOTI3MzFlMDcmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0In0.oZzWFcXNzKLWeWkE0YWBp8-TmoddsXoht-ky1n9Gt50)

Many thanks! It worked. <3
